version: '3.5'

services:
  postgres:
    container_name: postgresmenunda
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: menunda
      POSTGRES_USER: menunda
      POSTGRES_DB: menunda
    volumes:
      - dbdata:/var/lib/postgresql/data

volumes:
    dbdata: